apiVersion: v1
kind: Secret
metadata:
  name: llm-service-kernel-secret
  namespace: llm-service
type: Opaque
stringData:
  SEM_CACHE_MILVUS_USER: "root"
  SEM_CACHE_MILVUS_PASSWORD: "Milvus"
  MILVUS_TOKEN: "root:Milvus"
  RAG_OBJECT_STORE_ACCESS_KEY_ID: "llmbenchadmin"
  RAG_OBJECT_STORE_SECRET_ACCESS_KEY: "llmbenchsecretkey123"
