apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- fastapi-configmap.fullstack.yaml
- fastapi-secret.fullstack.yaml
- fastapi-service.yaml
- fastapi-deployment.fullstack.yaml
- fastapi-bootstrap-job.yaml
- rag-store-tenants-pvc.yaml
- tenant-ingest-input-pvc.yaml
