apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-store-tenants-pvc
  namespace: llm-service
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
