apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenant-ingest-input-pvc
  namespace: llm-service
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
