apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- restore-pvs.yaml
patches:
# Switch all PVCs from minikube's "standard" to EKS EBS gp3
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: ebs-gp3
# Pin all storage pods to the compute node (change instance-type in deploy/config.env)
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        node.kubernetes.io/instance-type: c7i.metal-24xl
