apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmd-model-pvc
  namespace: llm-d
spec:
  storageClassName: ebs-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
