apiVersion: v1
kind: Service
metadata:
  name: ms-local-decode-direct
  namespace: llm-d-local
spec:
  type: ClusterIP
  selector:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/role: decode
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP